# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build gjillo-api`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t gjillo-api`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system gjillo-api && \
          adduser --system -G gjillo-api gjillo-api

COPY dist/gjillo-api gjillo-api
RUN chown -R gjillo-api:gjillo-api .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix gjillo-api --omit=dev -f install

CMD [ "node", "gjillo-api" ]
