# Available options with descriptions at:
# https://github.com/anvilco/spectaql/blob/main/config-example.yml

spectaql:
  logoFile: graphql.ico
  faviconFile: graphql.ico
  displayAllServers: true
  targetDir: public/docs/api

introspection:
  removeTrailingPeriodFromDescriptions: false
#  url: http://localhost:4000/graphql
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2
  schemaFile: ./**/*.graphql

extensions:
  graphqlScalarExamples: true

info:
  title: Gjillo GraphQL API Reference
  description: This is the GraphQL API Reference for the Gjillo
#  description: Welcome to the party!
#  termsOfService: https://www.example.com/terms
#  contact:
#    name: API Support
#    url: http://www.example.com/support
#    email: support@example.com
#  license:
#    name: Apache 2.0
#    url: https://www.apache.org/licenses/LICENSE-2.0.html
#  x-introItems:
#    - title: Important thing 1
#      description: Some important stuff we wanted you to know. Supports `markdown`

servers:
  - url: https://gjillo.spookyless.net/api/graphql
    description: Production server
    production: true
  - url: http://localhost:4000/graphql
    description: Local development server
    production: false

#  - url: https://example.com/graphql
#    description: Production
#    production: true
#    headers:
#      - name: Authorization
#        example: Bearer <YOUR_TOKEN_HERE>
#        comment: Your foo from bar